# Generated by Django 2.0.4 on 2018-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_discount_apply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='apply_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preorder'), (2, 'Point of Sale'), (3, 'Post order')], default=2, verbose_name='Apply type'),
        ),
    ]
