# Generated by Django 2.0.4 on 2018-06-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neptune', '0002_auto_20180625_0341'),
        ('price', '0006_auto_20180621_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='shared_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neptune.SharedImage'),
        ),
    ]
