# Generated by Django 2.0.4 on 2018-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_auto_20180716_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='upper_bound',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
