# Generated by Django 2.0.9 on 2018-10-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20180717_0321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=set(),
        ),
    ]
