# Generated by Django 2.0.4 on 2018-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_client_users'),
        ('account', '0003_auto_20180504_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(through='hospital.Account', to='hospital.Client'),
        ),
    ]
