# Generated by Django 2.0.4 on 2018-05-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
