export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_COMPLETED = 'LOGOUT_COMPLETED';

export const MARKETSHARE_SUCCESS = 'MARKETSHARE_SUCCESS';
export const REP_CASE_SUCCESS = 'REP_CASE_SUCCESS';
export const SAVINGS_SUCCESS = 'SAVINGS_SUCCESS';
export const SAVINGS_UPDATE_CHART_FILTER = 'SAVINGS_UPDATE_CHART_FILTER';
export const BULK_INVENTORY_SUCCESS = 'BULK_INVENTORY_SUCCESS';
