# Generated by Django 2.0.4 on 2018-05-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Device category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Device name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Specialty')),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='specialty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='device.Specialty'),
        ),
    ]
