# Generated by Django 2.0.4 on 2018-05-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20180517_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='manufacturers/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Entry level'), (2, 'Advanced level')], default=1, verbose_name='Product level'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Model number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='Product image'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Manufacturer'),
        ),
    ]
