# Generated by Django 2.0.4 on 2018-05-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20180518_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': ' Products'},
        ),
    ]
