# Generated by Django 2.0.4 on 2018-05-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_discount_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientprice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientprice',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='discount',
            name='client_price',
        ),
        migrations.DeleteModel(
            name='ClientPrice',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
