# Generated by Django 2.0.4 on 2018-05-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20180525_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Feature name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Feature name')),
                ('value', models.CharField(max_length=255, verbose_name='Feature value')),
                ('category_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.CategoryFeature')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Product')),
            ],
        ),
    ]
