# Generated by Django 2.0.4 on 2018-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_categoryfeature_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Device category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'specialty')},
        ),
    ]
