# Generated by Django 2.0.4 on 2018-06-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
    ]
