# Generated by Django 2.0.4 on 2018-06-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neptune', '0001_initial'),
        ('device', '0013_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
        migrations.AddField(
            model_name='feature',
            name='shared_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neptune.SharedImage'),
        ),
    ]
