# Generated by Django 2.0.4 on 2018-06-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neptune', '0001_initial'),
        ('device', '0014_auto_20180622_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfeature',
            name='image',
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='shared_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neptune.SharedImage'),
        ),
    ]
