# Generated by Django 2.0.4 on 2018-06-25 03:58

from django.db import migrations, models
import functools
import neptune.utils


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_auto_20180625_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(neptune.utils.make_imagefield_filepath, *('categories',), **{}), verbose_name='Category image'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(neptune.utils.make_imagefield_filepath, *('manufacturers',), **{})),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(neptune.utils.make_imagefield_filepath, *('devices',), **{}), verbose_name='Product image'),
        ),
    ]
