# Generated by Django 2.0.4 on 2018-06-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_auto_20180625_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfeature',
            name='shared_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neptune.SharedImage'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='shared_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neptune.SharedImage'),
        ),
    ]
