# Generated by Django 2.0.4 on 2018-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_auto_20180625_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unassigned level'), (1, 'Entry level'), (2, 'Advanced level')], default=0, verbose_name='Product level'),
        ),
    ]
