# Generated by Django 2.0.4 on 2018-08-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_category_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('name', 'product')},
        ),
    ]
