# Generated by Django 2.0.4 on 2018-08-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_auto_20180801_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='short_name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Short name'),
        ),
    ]
