# Generated by Django 2.0.4 on 2018-08-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0023_manufacturer_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.CategoryFeature'),
        ),
    ]
