# Generated by Django 2.0.4 on 2018-06-25 03:41

from django.db import migrations, models
import functools
import neptune.models


class Migration(migrations.Migration):

    dependencies = [
        ('neptune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='image',
            field=models.ImageField(upload_to=functools.partial(neptune.models.make_imagefield_filepath, *('shared',), **{}), verbose_name='Shared image'),
        ),
    ]
