# Generated by Django 2.0.4 on 2018-05-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='hospital.Specialty'),
        ),
    ]
