# Generated by Django 2.0.4 on 2018-05-08 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='specialty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.Specialty'),
        ),
    ]
