# Generated by Django 2.0.4 on 2018-05-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_category_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='client',
            name='specialties',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
