# Generated by Django 2.0.4 on 2018-05-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('hospital', '0008_auto_20180508_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Product')),
            ],
        ),
    ]
