# Generated by Django 2.0.4 on 2018-05-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('hospital', '0009_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(through='hospital.Device', to='device.Product'),
        ),
    ]
