# Generated by Django 2.0.4 on 2018-05-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('hospital', '0010_client_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('client', 'product')},
        ),
    ]
