# Generated by Django 2.0.4 on 2018-05-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hospital.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='root_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
