# Generated by Django 2.0.4 on 2018-05-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20180510_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='root_parent_id',
        ),
    ]
