# Generated by Django 2.0.4 on 2018-05-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20180514_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Active Users'},
        ),
    ]
