# Generated by Django 2.0.4 on 2018-05-16 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0017_auto_20180516_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(through='hospital.Account', to=settings.AUTH_USER_MODEL),
        ),
    ]
