# Generated by Django 2.0.4 on 2018-05-25 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20180516_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number')),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot number')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier number')),
                ('expired_date', models.DateField()),
                ('purchased_date', models.DateField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Device')),
            ],
        ),
    ]
