# Generated by Django 2.0.4 on 2018-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Serial number'),
        ),
    ]
