# Generated by Django 2.0.4 on 2018-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20180525_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchased_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
