# Generated by Django 2.0.4 on 2018-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20180607_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hospital_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital part number'),
        ),
    ]
