# Generated by Django 2.0.4 on 2018-06-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_device_hospital_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unit cost'), (2, 'System cost')], default=1, verbose_name='Type'),
        ),
    ]
