# Generated by Django 2.0.4 on 2018-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20180613_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is used'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_type',
            field=models.SmallIntegerField(choices=[(1, 'Bulk'), (1, 'Consignment')], default=1, verbose_name='Purchased type'),
        ),
    ]
