# Generated by Django 2.0.4 on 2018-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20180618_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Physician access'), (2, 'Client Admin access'), (3, 'Sales Rep access')], default=1),
        ),
    ]
