# Generated by Django 2.0.4 on 2018-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_auto_20180625_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_type',
            field=models.SmallIntegerField(choices=[(1, 'Bulk'), (2, 'Consignment')], default=1, verbose_name='Purchased type'),
        ),
    ]
