# Generated by Django 2.0.4 on 2018-07-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_discount_shared_image'),
        ('hospital', '0030_item_rep_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounts',
            field=models.ManyToManyField(to='price.Discount'),
        ),
    ]
