# Generated by Django 2.0.4 on 2018-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_account_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Client Admin access'), (1, 'Physician access'), (3, 'Sales Rep access')], default=1),
        ),
    ]
