# Generated by Django 2.0.4 on 2018-08-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_auto_20180726_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rep_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.RepCase'),
        ),
    ]
