# Generated by Django 2.0.4 on 2018-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_auto_20180828_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
