# Generated by Django 2.0.4 on 2018-06-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0029_auto_20180626_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Complete')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Client')),
                ('owners', models.ManyToManyField(to='hospital.Account')),
            ],
        ),
    ]
