# Generated by Django 2.0.4 on 2018-07-04 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_item_cost_type'),
        ('device', '0019_auto_20180625_0916'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Entry level'), (2, 'Advanced level')], default=1, verbose_name='Device level')),
                ('cost_type', models.PositiveSmallIntegerField(choices=[(1, 'Unit cost'), (2, 'System cost')], default=1, verbose_name='Cost type')),
                ('avg', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Average purchase price')),
                ('min', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Lowest purchase price')),
                ('max', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Highest purchase price')),
                ('counter', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Client')),
            ],
        ),
    ]
