# Generated by Django 2.0.4 on 2018-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_purchaseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprice',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Lowest purchase price'),
        ),
    ]
