# Generated by Django 2.0.4 on 2018-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_purchaseprice_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprice',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unassigned level'), (1, 'Entry level'), (2, 'Advanced level')], default=0, verbose_name='Device level'),
        ),
    ]
