# Generated by Django 2.0.4 on 2018-08-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_auto_20180802_0737'),
        ('tracker', '0006_auto_20180726_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='repcase',
            name='physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_cases', to='hospital.Account'),
        ),
    ]
