# Generated by Django 2.0.4 on 2018-06-20 10:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0026_auto_20180618_1013'),
        ('device', '0011_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255, verbose_name='Patient')),
                ('procedure_datetime', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Complete'), (4, 'Cancelled')], default=1)),
                ('cost_type', models.PositiveSmallIntegerField(choices=[(1, 'Unit cost'), (2, 'System cost')], default=1)),
                ('discounts', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='physician_preferences',
            field=models.ManyToManyField(to='order.Preference'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Product'),
        ),
    ]
