# Generated by Django 2.0.4 on 2018-07-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_auto_20180726_0844'),
        ('order', '0002_remove_order_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Client'),
        ),
    ]
