# Generated by Django 2.0.4 on 2018-07-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0003_preference_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'device'), ('model__in', ('specialty', 'category'))), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='preference',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
