# Generated by Django 2.0.4 on 2018-09-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180726_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='preference',
            name='question',
        ),
        migrations.AddField(
            model_name='preference',
            name='name',
            field=models.CharField(default='Default physician preference list', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Preference'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Question'),
        ),
        migrations.AddField(
            model_name='preference',
            name='questions',
            field=models.ManyToManyField(through='order.Questionnaire', to='order.Question'),
        ),
    ]
