# Generated by Django 2.0.4 on 2018-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180904_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='name',
            field=models.CharField(default='Default', max_length=255, verbose_name='Name'),
        ),
    ]
