# Generated by Django 2.0.4 on 2018-09-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180904_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='physician_preferences',
        ),
        migrations.AddField(
            model_name='order',
            name='preference_questions',
            field=models.ManyToManyField(to='order.Question'),
        ),
    ]
