# Generated by Django 2.0.4 on 2018-09-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180905_0316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('preference', 'question')},
        ),
    ]
