# Generated by Django 2.0.4 on 2018-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20180905_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Question'),
        ),
    ]
